# Generated by Django 6.0.4 on 2026-06-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
