# =========================================
# اسم المشروع
# =========================================
spring.application.name=spring-boot-exam-template

# =========================================
# قاعدة البيانات
# غيّر YOUR_MYSQL_PASSWORD إلى باسورد MySQL عندك
# =========================================
spring.datasource.url=jdbc:mysql://localhost:3306/exam_app_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=YOUR_MYSQL_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate يعمل أو يعدّل الجداول تلقائيًا
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JSP
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp

server.error.include-message=always
server.error.include-binding-errors=always
